package com.qubit.android.sdk.api.tracker.event;

import com.google.gson.JsonObject;

/**
 * Interface of event.
 * Specific implementation can be generated by builder methods in {@link QBEvents}.
 */
public interface QBEvent {

  String getType();
  JsonObject toJsonObject();

}
